version: "3.9"
services:
  db:
    image: postgres:latest
    container_name: psql-container
    environment:
      POSTGRES_DB: aggregator
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./init/sql:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"